#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "CoverTypes.h"
#include "CoverObjectActor.generated.h"

class UCoverPointComponent;

/**
 * Actor grouping multiple cover points. Supports optional line-based auto generation on construction.
 */
UCLASS()
class ACoverObjectActor : public AActor
{
    GENERATED_BODY()

public:
    ACoverObjectActor();

protected:
    UPROPERTY(VisibleAnywhere, Category = "Cover|Root")
    USceneComponent* Root;

public:
    // Cover points (instanced components)
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Cover")
    TArray<UCoverPointComponent*> CoverPoints;

    // Auto-generate a line of cover points along LineLocalStart->LineLocalEnd on construction
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cover|AutoGen")
    bool bAutoGenerateLine = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cover|AutoGen")
    FVector LineLocalStart = FVector(0, -200, 0);

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cover|AutoGen")
    FVector LineLocalEnd = FVector(0, 200, 0);

    // Desired spacing between generated points
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cover|AutoGen", meta=(ClampMin="10", UIMin="10"))
    float PointSpacing = 80.f;

    // Normal for generated points (relative to actor)
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cover|AutoGen")
    FVector GeneratedLocalNormal = FVector(-1, 0, 0);

    // Shared thresholds for generated points
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cover|AutoGen")
    float GeneratedAcceptDistance = 85.f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cover|AutoGen")
    float GeneratedAcceptAngleDeg = 65.f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cover|AutoGen")
    float GeneratedSnapDistance = 45.f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cover|AutoGen")
    TEnumAsByte<ECoverHeight> GeneratedCoverHeight = ECoverHeight::Low;

    // Draw all points owned by this actor (for quick authoring checks)
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cover|Debug")
    bool bDrawDebug = true;

public:
    virtual void OnConstruction(const FTransform& Transform) override;

    UFUNCTION(BlueprintCallable, Category = "Cover")
    const TArray<UCoverPointComponent*>& GetCoverPoints() const { return CoverPoints; }

private:
    void ClearAutoGeneratedPoints();
    void GenerateLinePoints();
};
