#pragma once

#include "CoreMinimal.h"
#include "Components/SceneComponent.h"
#include "CoverTypes.h"
#include "CoverPointComponent.generated.h"

/**
 * A single cover point with direction (normal) and thresholds.
 * Debug drawing indicates eligibility; evaluation is pawn-agnostic (no Player dependency).
 */
UCLASS(ClassGroup=(Cover), meta=(BlueprintSpawnableComponent))
class UCoverPointComponent : public USceneComponent
{
    GENERATED_BODY()

public:
    UCoverPointComponent();

    // Relative normal pointing outward from the cover surface (character should face -Normal to take cover)
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cover|Config")
    FVector LocalNormal = FVector(-1.f, 0.f, 0.f);

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cover|Config")
    ECoverHeight CoverHeight = ECoverHeight::Low;

    // Max distance (cm) from cover point to be a valid candidate
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cover|Thresholds", meta=(ClampMin="0", UIMin="0"))
    float AcceptDistance = 85.f;

    // Max facing angle (deg) between Pawn forward and -WorldNormal to be valid
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cover|Thresholds", meta=(ClampMin="0", ClampMax="180", UIMin="0", UIMax="180"))
    float AcceptAngleDeg = 65.f;

    // Offset along -Normal from this component's location when snapping to cover
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cover|Config")
    float SnapDistance = 45.f;

    // Visuals
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cover|Debug")
    bool bDrawDebug = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cover|Debug")
    float DebugPointRadius = 10.f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cover|Debug")
    float DebugNormalLength = 40.f;

    // Auto-generated marker (used by CoverObjectActor to clean up)
    UPROPERTY(VisibleAnywhere, Category = "Cover|Internal")
    bool bAutoGenerated = false;

public:
    UFUNCTION(BlueprintCallable, Category = "Cover")
    FVector GetWorldNormal() const;

    // Evaluate if the given Pawn is a valid candidate for this cover point
    UFUNCTION(BlueprintCallable, Category = "Cover")
    void EvaluateCandidate(const APawn* Pawn, FCoverCandidateStatus& OutStatus) const;

    // Build a snap solution for this cover point (valid only if candidate met thresholds)
    UFUNCTION(BlueprintCallable, Category = "Cover")
    void BuildSolution(const APawn* Pawn, FCoverSolution& OutSolution) const;

    // Draw debug markers, optionally reflecting candidate status
    void DrawDebug(UWorld* World, const FCoverCandidateStatus* OptionalStatus = nullptr, bool bForceBest = false) const;
};

