#include "CoverObjectActor.h"
#include "CoverPointComponent.h"
#include "Components/SceneComponent.h"
#include "Engine/World.h"

ACoverObjectActor::ACoverObjectActor()
{
    Root = CreateDefaultSubobject<USceneComponent>(TEXT("Root"));
    RootComponent = Root;

    PrimaryActorTick.bCanEverTick = false;
}

void ACoverObjectActor::OnConstruction(const FTransform& Transform)
{
    Super::OnConstruction(Transform);

    if (bAutoGenerateLine)
    {
        ClearAutoGeneratedPoints();
        GenerateLinePoints();
    }

    if (bDrawDebug)
    {
        for (const UCoverPointComponent* Point : CoverPoints)
        {
            if (Point)
            {
                Point->DrawDebug(GetWorld(), nullptr, false);
            }
        }
    }
}

void ACoverObjectActor::ClearAutoGeneratedPoints()
{
    // Remove components flagged as auto-generated
    for (int32 i = CoverPoints.Num() - 1; i >= 0; --i)
    {
        if (UCoverPointComponent* Point = CoverPoints[i])
        {
            if (Point->bAutoGenerated)
            {
                Point->DestroyComponent();
                CoverPoints.RemoveAt(i);
            }
        }
        else
        {
            CoverPoints.RemoveAt(i);
        }
    }
}

void ACoverObjectActor::GenerateLinePoints()
{
    const FVector LocalDelta = LineLocalEnd - LineLocalStart;
    const float Length = LocalDelta.Size();
    if (Length <= KINDA_SMALL_NUMBER || PointSpacing <= KINDA_SMALL_NUMBER)
    {
        return;
    }

    const int32 NumSegments = FMath::Max(1, FMath::FloorToInt(Length / PointSpacing));
    const FVector LocalStep = LocalDelta / static_cast<float>(NumSegments);

    for (int32 i = 0; i <= NumSegments; ++i)
    {
        const FVector LocalPos = LineLocalStart + LocalStep * static_cast<float>(i);
        UCoverPointComponent* Point = NewObject<UCoverPointComponent>(this, UCoverPointComponent::StaticClass());
        Point->SetupAttachment(RootComponent);
        Point->RegisterComponent();
        Point->SetRelativeLocation(LocalPos);
        Point->LocalNormal = GeneratedLocalNormal;
        Point->AcceptDistance = GeneratedAcceptDistance;
        Point->AcceptAngleDeg = GeneratedAcceptAngleDeg;
        Point->SnapDistance = GeneratedSnapDistance;
        Point->CoverHeight = (ECoverHeight)GeneratedCoverHeight.GetValue();
        Point->bAutoGenerated = true;

        CoverPoints.Add(Point);
    }
}

